port: 2355
save_video: true
seed: 0

PipelineParams:
  convert_SHs_python: False #true = using direct rgb
ModelParams:
  workspace: wizard
  sh_degree: 0
  bg_aug_ratio: 0.66
  _source_path: /scratch/rgoel15/lucid/wizard/
  _model_path: /scratch/rgoel15/lucid/wizard/

GuidanceParams:
  model_key: 'stabilityai/stable-diffusion-2-1-base'
  text: 'a Wizard standing before a Wooden Desk, gazing into a Crystal Ball perched atop the Wooden Desk, with a Stack of Ancient Spell Books perched atop the Wooden Desk, cartoon, blender, photorealistic, 8K, HDR.'
  prompt_obj: ['a Wizard: bearded, standing, focused', 'a Wooden Desk: large, sturdy, carved with runes, aged', 
    'a Crystal Ball with ornate stand: small, glowing, transparent, mystic',  'a Stack of Ancient Spell Books: small, leather-bound, weathered, rune-etched']
  prompt_edge: ['a Wizard standing before a Wooden Desk, cartoon, blender', 'a Crystal Ball perched atop a Wooden Desk, cartoon, blender',
    'a Stack of Ancient Spell Books next to a Crystal Ball, cartoon, blender', 'a Stack of Ancient Spell Books perched atop a Wooden Desk, cartoon, blender']
  negative: 'ugly, bad anatomy, blurry, pixelated obscure, unnatural colors, poor lighting, dull, and unclear, cropped, lowres, low quality, artifacts, duplicate, morbid, mutilated, poorly drawn face, deformed, dehydrated, bad proportions'
  edge_list: [[0,1],[1,2],[2,3],[1,3]]
  center_params: [[-0.25,0.1,0.],[0.24,0.12,0.],[0.25,0.13,0.2],[0.28,-0.16,0.2]]
  radius_params: [0.5,0.5,0.3,0.3]
  num_objs: 4
  inverse_text: ''
  perpneg: true
  C_batch_size: 4
  max_t_range: 0.98
  lambda_guidance: 0.1
  guidance_scale: 7.5
  denoise_guidance_scale: 1.0
  noise_seed: 0

  ddim_inv: true
  annealing_intervals: true

  xs_delta_t: 200
  xs_inv_steps: 5
  xs_eta: 0.0
  
  delta_t: 50
  delta_t_start: 100

GenerateCamParams:
  init_shape: 'pointe'
  init_prompt: ['a human.', 'a table.', 'a ball.', 'a book stack.']
  use_pointe_rgb: false
  init_num_pts: 100_000
  num_objs: 4
  center_params: [[-0.25,0.1,0.],[0.24,0.12,0.],[0.25,0.13,0.2],[0.28,-0.16,0.2]]
  radius_params: [0.5,0.5,0.3,0.3]
  phi_range: [-80, 80]
  max_phi_range: [-180, 180]
  rand_cam_gamma: 1.5

  theta_range: [45, 90]
  max_theta_range: [45, 90]

  radius_range: [5.2, 5.5] #[3.8, 4.5] #[3.0, 3.5]
  max_radius_range: [3.5, 5.0] #[3.8, 4.5] #[3.0, 3.5]
  default_radius: 3.5
 
  default_fovy: 0.55
  fovy_range: [0.32, 0.60]
  max_fovy_range: [0.16, 0.60]

OptimizationParams:
  iterations: 5000
  save_process: True
  pro_frames_num: 600
  pro_render_45: False
  warmup_iter: 1500 # 2500
  num_objs: 4
  edge_list: [[0,1],[1,2],[2,3],[1,3]]

  as_latent_ratio : 0.2
  geo_iter : 0
  densify_from_iter: 25
  densify_until_iter: 3000
  percent_dense: 0.003
  densify_grad_threshold: 0.00075
  progressive_view_iter: 500 #1500
  opacity_reset_interval: 60 #500

  scale_up_cameras_iter: 500
  fovy_scale_up_factor: [0.75, 1.1]
  phi_scale_up_factor: 1.5